### ISSUE TITLE
Add / teach all trail managers

### ISSUE THREAD

**Issue by omundy** [omundy/tarheeltrailblazers-theme#11]
- [x] Once site is nearly finished, add all trail manager accounts to WP (Owen)
- [x] Set a time (in a meeting?) to go over editing status (Bryan)

**Comment by SirNotAppearing** [comment]
What information should I provide for trail managers? Just name and email?

**Comment by omundy** [comment]
> What information should I provide for trail managers? Just name and email?

Yes, that is it.
