### ISSUE TITLE
Add hover states for difficulty and status, grab MTB project SVGs to display

### ISSUE THREAD

**Issue by omundy** [omundy/tarheeltrailblazers-theme#15]

**Comment by omundy** [comment]
@SirNotAppearing I found a tool tip function. What do you think about these?


![image](https://user-images.githubusercontent.com/279945/75184304-2f21e600-5712-11ea-8362-ce886eb0b56c.png)
Difficulty

![image](https://user-images.githubusercontent.com/279945/75184279-24ffe780-5712-11ea-9a1b-f619b23f22b7.png)
Tiny status

Trail page status
![image](https://user-images.githubusercontent.com/279945/75184547-8e7ff600-5712-11ea-8544-a55db6efb19d.png)

**Comment by SirNotAppearing** [comment]
Looks good to me!

________________________________

**Comment by omundy** [comment]
Live now!
